<?php

namespace App\Console\Commands;

use App\Models\Product;
use App\Models\WebsiteCategory;
use App\Models\WebsiteProject;
use App\Services\SeoService;
use Illuminate\Console\Command;

class SeoAutoGenerateCommand extends Command
{
    protected $signature = 'seo:auto-generate {--force : Regenerate even for manually edited records}';

    protected $description = 'Auto-generate SEO meta for all products, projects, and categories using templates';

    public function handle(SeoService $seoService): int
    {
        $models = [
            Product::class => 'products',
            WebsiteProject::class => 'projects',
            WebsiteCategory::class => 'categories',
        ];

        $created = 0;
        $updated = 0;
        $skipped = 0;

        foreach ($models as $modelClass => $label) {
            $count = $modelClass::count();
            $this->info("Processing {$label}: {$count} found");

            $modelClass::chunk(100, function ($instances) use ($seoService, &$created, &$updated, &$skipped) {
                foreach ($instances as $model) {
                    $existing = $model->seoMeta;

                    if ($existing && ! $existing->is_autogenerated && ! $this->option('force')) {
                        $skipped++;
                        continue;
                    }

                    if ($existing) {
                        $seoService->applyTemplate($model);
                        $updated++;
                    } else {
                        $seoService->applyTemplate($model);
                        $created++;
                    }
                }
            });
        }

        $this->info("Done! Created: {$created}, Updated: {$updated}, Skipped: {$skipped}");

        return Command::SUCCESS;
    }
}
