<?php

namespace Database\Seeders;

use App\Models\SeoMeta;
use Illuminate\Database\Seeder;

class SeoSeeder extends Seeder
{
    public function run(): void
    {
        $staticPages = config('seo.static_pages', []);

        foreach ($staticPages as $slug => $data) {
            SeoMeta::updateOrCreate(
                [
                    'seoable_type' => 'App\\Models\\StaticPage',
                    'seoable_id' => 0,
                ],
                array_merge($data, [
                    'is_autogenerated' => false,
                    'status' => true,
                ])
            );
        }
    }
}
