<?php

namespace App\Services;

use App\Models\Product;
use App\Models\SeoMeta;
use App\Models\WebsiteCategory;
use App\Models\WebsiteProject;

class SeoDashboardService
{
    protected array $models = [
        Product::class,
        WebsiteProject::class,
        WebsiteCategory::class,
    ];

    public function getHealthScore(): int
    {
        $weights = config('seo.score_weights', [
            'coverage' => 30,
            'active' => 20,
            'description' => 20,
            'og' => 15,
            'schema' => 15,
        ]);

        $coverageScore = $this->coverageScore() * ($weights['coverage'] / 100);
        $activeScore = $this->activeScore() * ($weights['active'] / 100);
        $descriptionScore = $this->descriptionScore() * ($weights['description'] / 100);
        $ogScore = $this->ogScore() * ($weights['og'] / 100);
        $schemaScore = $this->schemaScore() * ($weights['schema'] / 100);

        return (int) round($coverageScore + $activeScore + $descriptionScore + $ogScore + $schemaScore);
    }

    public function getStats(): array
    {
        $seoCount = SeoMeta::count();

        $counts = [];
        foreach ($this->models as $modelClass) {
            $modelCount = $modelClass::count();
            $seoCountForType = SeoMeta::where('seoable_type', $modelClass)->count();
            $counts[class_basename($modelClass)] = [
                'total' => $modelCount,
                'with_seo' => $seoCountForType,
            ];
        }

        return [
            'total_seo_records' => $seoCount,
            'by_type' => $counts,
            'active' => SeoMeta::where('status', true)->count(),
            'inactive' => SeoMeta::where('status', false)->count(),
            'auto' => SeoMeta::where('is_autogenerated', true)->count(),
            'manual' => SeoMeta::where('is_autogenerated', false)->count(),
            'missing_description' => SeoMeta::whereNull('meta_description')->count(),
            'missing_title' => SeoMeta::whereNull('meta_title')->count(),
            'missing_og' => SeoMeta::whereNull('og_title')->count(),
            'missing_schema' => SeoMeta::whereNull('schema_type')->count(),
        ];
    }

    public function getAlerts(): array
    {
        $duplicateTitles = SeoMeta::select('meta_title')
            ->whereNotNull('meta_title')
            ->groupBy('meta_title')
            ->havingRaw('COUNT(*) > 1')
            ->get()
            ->pluck('meta_title');

        $duplicateDescriptions = SeoMeta::select('meta_description')
            ->whereNotNull('meta_description')
            ->groupBy('meta_description')
            ->havingRaw('COUNT(*) > 1')
            ->get()
            ->pluck('meta_description');

        return [
            'duplicate_titles' => $duplicateTitles,
            'duplicate_descriptions' => $duplicateDescriptions,
            'missing_descriptions_count' => SeoMeta::whereNull('meta_description')->count(),
            'missing_titles_count' => SeoMeta::whereNull('meta_title')->count(),
        ];
    }

    public function runAudit(): int
    {
        $updated = 0;

        SeoMeta::chunk(100, function ($metas) use (&$updated) {
            foreach ($metas as $meta) {
                $score = $this->calculateRecordScore($meta);
                $meta->updateQuietly([
                    'seo_score' => $score,
                    'last_audited_at' => now(),
                ]);
                $updated++;
            }
        });

        return $updated;
    }

    protected function calculateRecordScore(SeoMeta $meta): int
    {
        $score = 0;

        if ($meta->meta_title) $score += 25;
        if ($meta->meta_description) $score += 25;
        if ($meta->og_title || $meta->og_description || $meta->og_image) $score += 20;
        if ($meta->twitter_title || $meta->twitter_description) $score += 15;
        if ($meta->schema_type) $score += 15;

        return min($score, 100);
    }

    protected function coverageScore(): float
    {
        $totalModels = 0;
        $totalWithSeo = 0;

        foreach ($this->models as $modelClass) {
            $totalModels += $modelClass::count();
            $totalWithSeo += SeoMeta::where('seoable_type', $modelClass)->count();
        }

        if ($totalModels === 0) return 100;
        return ($totalWithSeo / $totalModels) * 100;
    }

    protected function activeScore(): float
    {
        $total = SeoMeta::count();
        if ($total === 0) return 100;
        return (SeoMeta::where('status', true)->count() / $total) * 100;
    }

    protected function descriptionScore(): float
    {
        $total = SeoMeta::count();
        if ($total === 0) return 100;
        return (SeoMeta::whereNotNull('meta_description')->count() / $total) * 100;
    }

    protected function ogScore(): float
    {
        $total = SeoMeta::count();
        if ($total === 0) return 100;
        return (SeoMeta::whereNotNull('og_title')->count() / $total) * 100;
    }

    protected function schemaScore(): float
    {
        $total = SeoMeta::count();
        if ($total === 0) return 100;
        return (SeoMeta::whereNotNull('schema_type')->count() / $total) * 100;
    }
}
