<?php

namespace App\Services;

use App\Models\Product;
use App\Models\SiteSetting;
use App\Models\WebsiteCategory;
use App\Models\WebsiteProject;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class SeoService
{
    public function applyTemplate(Model $model): ?\App\Models\SeoMeta
    {
        $type = class_basename($model);
        $templates = config('seo.templates.'.$type, []);

        if (empty($templates)) {
            return null;
        }

        $variables = $this->getVariables($model);
        $data = [];

        foreach ($templates as $field => $template) {
            if (is_array($template)) {
                $data[$field] = array_map(fn($t) => $this->render($t, $variables), $template);
            } else {
                $data[$field] = $this->render($template, $variables);
            }
        }

        if (isset($data['focus_keywords']) && is_string($data['focus_keywords'])) {
            $data['focus_keywords'] = $this->parseKeywords($data['focus_keywords']);
        }

        $seoMeta = $model->seoMeta()->firstOrCreate(
            ['seoable_type' => get_class($model), 'seoable_id' => $model->id],
            array_merge($data, ['is_autogenerated' => true, 'status' => true])
        );

        if (! $seoMeta->wasRecentlyCreated && $seoMeta->is_autogenerated) {
            $seoMeta->update($data);
        }

        return $seoMeta;
    }

    public function render(string $template, array $variables): string
    {
        foreach ($variables as $key => $value) {
            $template = str_replace('{'.$key.'}', $value ?? '', $template);
        }

        return $template;
    }

    public function parseKeywords(string $keywordString): array
    {
        return array_map('trim', explode(',', $keywordString));
    }

    public function buildJsonLd(object $model): ?array
    {
        $meta = $model->seoMeta;
        if (! $meta || ! $meta->schema_type) {
            return null;
        }

        $schema = [
            '@context' => 'https://schema.org',
            '@type' => $meta->schema_type,
        ];

        if (isset($meta->meta_title) && $meta->meta_title) {
            $schema['name'] = $meta->meta_title;
        }
        if (isset($meta->meta_description) && $meta->meta_description) {
            $schema['description'] = $meta->meta_description;
        }
        if (isset($meta->og_image) && $meta->og_image) {
            $schema['image'] = storage_url($meta->og_image);
        }
        if (isset($meta->canonical_url) && $meta->canonical_url) {
            $schema['url'] = $meta->canonical_url;
        }

        if ($model instanceof Product) {
            $product = $model->product_name;
            $schema['@type'] = 'Product';
            $schema['name'] = $product;
            $schema['brand'] = [
                '@type' => 'Brand',
                'name' => SiteSetting::getValue('site_name', config('app.name')),
            ];
            $schema['category'] = $model->project?->category?->name ?? 'Clothing';

            if ($model->project?->details) {
                $schema['description'] = $model->project->details;
            }
            if ($model->project?->images?->first()) {
                $schema['image'] = storage_url($model->project->images->first()->image_path);
            }
            if ($model->price) {
                $schema['offers'] = [
                    '@type' => 'Offer',
                    'price' => $model->price,
                    'priceCurrency' => 'BDT',
                    'availability' => ($model->stocks()->sum('quantity') > 0) ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock',
                ];
            }

            $sizes = $model->stocks()->distinct()->pluck('size')->filter()->values();
            if ($sizes->isNotEmpty()) {
                $schema['size'] = $sizes->toArray();
            }
        }

        if ($model instanceof WebsiteProject) {
            $schema['@type'] = 'Product';
            $schema['name'] = $model->product?->product_name ?? $model->slug;
            $schema['brand'] = [
                '@type' => 'Brand',
                'name' => SiteSetting::getValue('site_name', config('app.name')),
            ];
            $schema['category'] = $model->category?->name ?? 'Clothing';
            if ($model->details) {
                $schema['description'] = $model->details;
            }
            if ($model->product?->price) {
                $schema['offers'] = [
                    '@type' => 'Offer',
                    'price' => $model->product->price,
                    'priceCurrency' => 'BDT',
                    'availability' => ($model->product->stocks()->sum('quantity') > 0) ? 'https://schema.org/InStock' : 'https://schema.org/OutOfStock',
                ];
            }
            $sizes = $model->product?->stocks()->distinct()->pluck('size')->filter()->values();
            if ($sizes?->isNotEmpty()) {
                $schema['size'] = $sizes->toArray();
            }
        }

        return $schema;
    }

    public function validateJsonLd(array $schema): bool
    {
        if (! isset($schema['@context'], $schema['@type'])) {
            return false;
        }

        if ($schema['@context'] !== 'https://schema.org') {
            return false;
        }

        $validTypes = [
            'Product', 'WebPage', 'Organization', 'ClothingStore',
            'LocalBusiness', 'Service', 'BreadcrumbList', 'FAQPage',
            'Article', 'CollectionPage', 'AboutPage', 'ContactPage',
        ];

        return in_array($schema['@type'], $validTypes);
    }

    protected function getVariables(Model $model): array
    {
        $variables = [
            'site_name' => SiteSetting::getValue('site_name', config('app.name')),
            'current_year' => now()->format('Y'),
            'brand' => SiteSetting::getValue('site_name', config('app.name')),
        ];

        if ($model instanceof Product) {
            $variables['title'] = $model->product_name;
            $variables['name'] = $model->product_name;
            $variables['description'] = $model->project?->details ?? '';
            $variables['category'] = $model->project?->category?->name ?? 'Clothing';
            $variables['price'] = number_format($model->price ?? 0, 2);
            $variables['sku'] = $model->product_code ?? '';
            $variables['url'] = $this->buildProductUrl($model);
            $variables['sizes'] = $model->stocks()->distinct()->pluck('size')->filter()->implode(', ');
            $variables['brand'] = SiteSetting::getValue('site_name', config('app.name'));
        }

        if ($model instanceof WebsiteProject) {
            $variables['title'] = $model->product?->product_name ?? $model->slug;
            $variables['name'] = $model->product?->product_name ?? $model->slug;
            $variables['description'] = $model->details ?? '';
            $variables['category'] = $model->category?->name ?? 'Clothing';
            $variables['url'] = shop_project_url($model);
            $variables['sizes'] = $model->product?->stocks()->distinct()->pluck('size')->filter()->implode(', ');
            $variables['brand'] = SiteSetting::getValue('site_name', config('app.name'));
        }

        if ($model instanceof WebsiteCategory) {
            $variables['title'] = $model->name;
            $variables['name'] = $model->name;
            $variables['description'] = $model->description ?? '';
            $variables['url'] = route('shop.products.index');
            $variables['brand'] = SiteSetting::getValue('site_name', config('app.name'));
        }

        return $variables;
    }

    protected function buildProductUrl(Product $model): string
    {
        $project = $model->project;
        if ($project) {
            $category = $project->category?->slug;
            $slug = $project->slug;

            return $category ? url("/{$category}/{$slug}") : url("/{$slug}");
        }

        return url('/'.Str::slug($model->product_name));
    }
}
