<?php

namespace App\Observers;

use App\Models\Product;
use App\Services\SeoService;

class ProductObserver
{
    protected array $relevantFields = ['product_name', 'product_code', 'price'];

    public function created(Product $product): void
    {
        app(SeoService::class)->applyTemplate($product);
    }

    public function updated(Product $product): void
    {
        if ($this->relevantContentChanged($product)) {
            $meta = $product->seoMeta;
            if ($meta && $meta->is_autogenerated) {
                app(SeoService::class)->applyTemplate($product);
            }
        }
    }

    public function deleted(Product $product): void
    {
        $product->seoMeta()->delete();
    }

    protected function relevantContentChanged(Product $product): bool
    {
        return $product->wasChanged($this->relevantFields);
    }
}
