<?php

namespace App\Observers;

use App\Models\WebsiteProject;
use App\Services\SeoService;

class WebsiteProjectObserver
{
    protected array $relevantFields = ['slug', 'details', 'category_id'];

    public function created(WebsiteProject $project): void
    {
        app(SeoService::class)->applyTemplate($project);
    }

    public function updated(WebsiteProject $project): void
    {
        if ($this->relevantContentChanged($project)) {
            $meta = $project->seoMeta;
            if ($meta && $meta->is_autogenerated) {
                app(SeoService::class)->applyTemplate($project);
            }
        }
    }

    public function deleted(WebsiteProject $project): void
    {
        $project->seoMeta()->delete();
    }

    protected function relevantContentChanged(WebsiteProject $project): bool
    {
        return $project->wasChanged($this->relevantFields);
    }
}
