<?php

namespace App\Observers;

use App\Models\WebsiteCategory;
use App\Services\SeoService;

class WebsiteCategoryObserver
{
    protected array $relevantFields = ['name', 'description'];

    public function created(WebsiteCategory $category): void
    {
        app(SeoService::class)->applyTemplate($category);
    }

    public function updated(WebsiteCategory $category): void
    {
        if ($this->relevantContentChanged($category)) {
            $meta = $category->seoMeta;
            if ($meta && $meta->is_autogenerated) {
                app(SeoService::class)->applyTemplate($category);
            }
        }
    }

    public function deleted(WebsiteCategory $category): void
    {
        $category->seoMeta()->delete();
    }

    protected function relevantContentChanged(WebsiteCategory $category): bool
    {
        return $category->wasChanged($this->relevantFields);
    }
}
