<x-card class="overflow-x-auto">
    <table class="w-full text-sm">
        <thead>
            <tr class="border-b border-[#232A36] text-left text-[#94A3B8]">
                <th class="pb-3 font-medium">Type</th>
                <th class="pb-3 font-medium">Name</th>
                <th class="pb-3 font-medium">Meta Title</th>
                <th class="pb-3 font-medium">Meta Description</th>
                <th class="pb-3 font-medium">Source</th>
                <th class="pb-3 font-medium">Status</th>
                <th class="pb-3 font-medium text-right">Actions</th>
            </tr>
        </thead>
        <tbody>
            @forelse($seoMetas as $seo)
            <tr class="border-b border-[#232A36]/50 hover:bg-[#1C2333]">
                <td class="py-3 text-[#E6EDF3]">
                    <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium
                        {{ class_basename($seo->seoable_type) === 'Product' ? 'bg-[#3B82F6]/10 text-[#3B82F6]' :
                           (class_basename($seo->seoable_type) === 'WebsiteProject' ? 'bg-[#8B5CF6]/10 text-[#8B5CF6]' : 'bg-[#F59E0B]/10 text-[#F59E0B]') }}">
                        {{ class_basename($seo->seoable_type) }}
                    </span>
                </td>
                <td class="py-3 text-[#E6EDF3]">{{ $seo->seoable?->name ?? $seo->seoable?->title ?? '—' }}</td>
                <td class="py-3 text-[#94A3B8] max-w-[200px] truncate">{{ $seo->meta_title ?? '—' }}</td>
                <td class="py-3 text-[#94A3B8] max-w-[250px] truncate">{{ $seo->meta_description ?? '—' }}</td>
                <td class="py-3">
                    <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium {{ $seo->is_autogenerated ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#EF4444]/10 text-[#EF4444]' }}">
                        {{ $seo->is_autogenerated ? 'Auto' : 'Manual' }}
                    </span>
                </td>
                <td class="py-3">
                    <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium {{ $seo->status ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#6B7280]/10 text-[#6B7280]' }}">
                        {{ $seo->status ? 'Active' : 'Inactive' }}
                    </span>
                </td>
                <td class="py-3 text-right">
                    <div class="flex items-center justify-end gap-2">
                        <a href="{{ admin_route('seo.edit', $seo->id) }}" class="rounded-lg bg-[#3B82F6]/10 px-3 py-1.5 text-xs font-medium text-[#3B82F6] hover:bg-[#3B82F6]/20">
                            <i class="fas fa-edit"></i> Edit
                        </a>
                        @if($seo->is_autogenerated)
                        <a href="{{ admin_route('seo.reset-template', $seo->id) }}" onclick="return confirm('Reset to template?')" class="rounded-lg bg-[#F59E0B]/10 px-3 py-1.5 text-xs font-medium text-[#F59E0B] hover:bg-[#F59E0B]/20">
                            <i class="fas fa-undo"></i>
                        </a>
                        @endif
                        <form action="{{ admin_route('seo.destroy', $seo->id) }}" method="POST" class="inline" onsubmit="return confirm('Delete this SEO meta?')">
                            @csrf @method('DELETE')
                            <button type="submit" class="rounded-lg bg-[#EF4444]/10 px-3 py-1.5 text-xs font-medium text-[#EF4444] hover:bg-[#EF4444]/20">
                                <i class="fas fa-trash"></i>
                            </button>
                        </form>
                    </div>
                </td>
            </tr>
            @empty
            <tr>
                <td colspan="7" class="py-12 text-center text-[#94A3B8]">
                    <i class="fas fa-search mb-3 text-3xl text-[#232A36]"></i>
                    <p>No SEO records found.</p>
                </td>
            </tr>
            @endforelse
        </tbody>
    </table>
</x-card>

@if ($seoMetas->hasPages())
@php
    $cp = $seoMetas->currentPage();
    $lp = $seoMetas->lastPage();
    $start = max(1, $cp - 2);
    $end = min($lp, $cp + 2);
@endphp
<div class="mt-4 flex items-center justify-between">
    <div class="text-sm text-[#94A3B8]">
        Showing {{ $seoMetas->firstItem() }}–{{ $seoMetas->lastItem() }} of {{ $seoMetas->total() }}
    </div>
    <div class="flex items-center gap-1">
        <button onclick="seoGoToPage({{ $cp - 1 }})" {{ $cp === 1 ? 'disabled' : '' }} class="rounded-lg border border-[#232A36] px-3 py-1.5 text-sm text-[#94A3B8] hover:bg-[#1C2333] disabled:opacity-30 disabled:cursor-not-allowed">Prev</button>
        @if ($start > 1)
        <button onclick="seoGoToPage(1)" class="rounded-lg px-3 py-1.5 text-sm text-[#94A3B8] hover:bg-[#1C2333]">1</button>
        @if ($start > 2) <span class="px-1 text-[#94A3B8]">...</span> @endif
        @endif
        @for ($p = $start; $p <= $end; $p++)
        <button onclick="seoGoToPage({{ $p }})" class="rounded-lg px-3 py-1.5 text-sm {{ $p === $cp ? 'bg-[#3B82F6] text-white' : 'text-[#94A3B8] hover:bg-[#1C2333]' }}">{{ $p }}</button>
        @endfor
        @if ($end < $lp)
        @if ($end < $lp - 1) <span class="px-1 text-[#94A3B8]">...</span> @endif
        <button onclick="seoGoToPage({{ $lp }})" class="rounded-lg px-3 py-1.5 text-sm text-[#94A3B8] hover:bg-[#1C2333]">{{ $lp }}</button>
        @endif
        <button onclick="seoGoToPage({{ $cp + 1 }})" {{ $cp === $lp ? 'disabled' : '' }} class="rounded-lg border border-[#232A36] px-3 py-1.5 text-sm text-[#94A3B8] hover:bg-[#1C2333] disabled:opacity-30 disabled:cursor-not-allowed">Next</button>
    </div>
</div>
@endif
