<x-layouts.app title="Edit SEO Meta">
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <div>
                <h1 class="text-2xl font-bold text-[#E6EDF3]">Edit SEO Meta</h1>
                <p class="text-sm text-[#94A3B8]">
                    {{ class_basename($seoMeta->seoable_type) }}: {{ $seoMeta->seoable?->name ?? $seoMeta->seoable?->title ?? '—' }}
                </p>
            </div>
            <div class="flex gap-2">
                @if($seoMeta->is_autogenerated)
                <a href="{{ admin_route('seo.reset-template', $seoMeta->id) }}" onclick="return confirm('Reset to template?')" class="inline-flex items-center gap-2 rounded-xl bg-[#F59E0B] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#D97706]">
                    <i class="fas fa-undo"></i> Reset to Template
                </a>
                @endif
                <a href="{{ admin_route('seo.index') }}" class="inline-flex items-center gap-2 rounded-xl border border-[#232A36] px-4 py-2.5 text-sm font-medium text-[#94A3B8] hover:bg-[#1C2333]">
                    <i class="fas fa-arrow-left"></i> Back
                </a>
            </div>
        </div>

        {{-- Source Badge --}}
        <div class="flex items-center gap-3">
            <span class="inline-flex items-center rounded-full px-3 py-1 text-xs font-medium {{ $seoMeta->is_autogenerated ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#EF4444]/10 text-[#EF4444]' }}">
                {{ $seoMeta->is_autogenerated ? 'Auto-Generated' : 'Manual Edit' }}
            </span>
            <span class="inline-flex items-center rounded-full px-3 py-1 text-xs font-medium {{ $seoMeta->status ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#6B7280]/10 text-[#6B7280]' }}">
                {{ $seoMeta->status ? 'Active' : 'Inactive' }}
            </span>
        </div>

        <form action="{{ admin_route('seo.update', $seoMeta->id) }}" method="POST">
            @csrf
            @method('PUT')

            <div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
                {{-- Basic SEO --}}
                <x-card class="p-6">
                    <h3 class="mb-4 text-lg font-semibold text-[#E6EDF3]">Basic SEO</h3>
                    <div class="space-y-4">
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Meta Title</label>
                            <input type="text" name="meta_title" value="{{ old('meta_title', $seoMeta->meta_title) }}" maxlength="70" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                            <p class="mt-1 text-xs text-[#94A3B8]">{{ strlen($seoMeta->meta_title ?? '') }}/70 characters</p>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Meta Description</label>
                            <textarea name="meta_description" rows="3" maxlength="500" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('meta_description', $seoMeta->meta_description) }}</textarea>
                            <p class="mt-1 text-xs text-[#94A3B8]">{{ strlen($seoMeta->meta_description ?? '') }}/500 characters</p>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Focus Keywords</label>
                            <input type="text" name="focus_keywords" value="{{ old('focus_keywords', implode(', ', $seoMeta->focus_keywords ?? [])) }}" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                            <p class="mt-1 text-xs text-[#94A3B8]">Comma-separated keywords</p>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Robots</label>
                            <select name="robots" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                                <option value="index,follow" {{ ($seoMeta->robots ?? 'index,follow') === 'index,follow' ? 'selected' : '' }}>Index, Follow</option>
                                <option value="noindex,follow" {{ ($seoMeta->robots ?? '') === 'noindex,follow' ? 'selected' : '' }}>NoIndex, Follow</option>
                                <option value="index,nofollow" {{ ($seoMeta->robots ?? '') === 'index,nofollow' ? 'selected' : '' }}>Index, NoFollow</option>
                                <option value="noindex,nofollow" {{ ($seoMeta->robots ?? '') === 'noindex,nofollow' ? 'selected' : '' }}>NoIndex, NoFollow</option>
                            </select>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Canonical URL</label>
                            <input type="url" name="canonical_url" value="{{ old('canonical_url', $seoMeta->canonical_url) }}" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                    </div>
                </x-card>

                {{-- Open Graph --}}
                <x-card class="p-6">
                    <h3 class="mb-4 text-lg font-semibold text-[#E6EDF3]">Open Graph</h3>
                    <div class="space-y-4">
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">OG Title</label>
                            <input type="text" name="og_title" value="{{ old('og_title', $seoMeta->og_title) }}" maxlength="70" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">OG Description</label>
                            <textarea name="og_description" rows="2" maxlength="200" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('og_description', $seoMeta->og_description) }}</textarea>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">OG Image Path</label>
                            <input type="text" name="og_image" value="{{ old('og_image', $seoMeta->og_image) }}" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">OG URL</label>
                            <input type="url" name="og_url" value="{{ old('og_url', $seoMeta->og_url) }}" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                    </div>
                </x-card>

                {{-- Twitter Card --}}
                <x-card class="p-6">
                    <h3 class="mb-4 text-lg font-semibold text-[#E6EDF3]">Twitter Card</h3>
                    <div class="space-y-4">
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Twitter Title</label>
                            <input type="text" name="twitter_title" value="{{ old('twitter_title', $seoMeta->twitter_title) }}" maxlength="70" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Twitter Description</label>
                            <textarea name="twitter_description" rows="2" maxlength="200" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('twitter_description', $seoMeta->twitter_description) }}</textarea>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Twitter Image Path</label>
                            <input type="text" name="twitter_image" value="{{ old('twitter_image', $seoMeta->twitter_image) }}" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                        </div>
                    </div>
                </x-card>

                {{-- Schema & Hreflang --}}
                <x-card class="p-6">
                    <h3 class="mb-4 text-lg font-semibold text-[#E6EDF3]">Advanced</h3>
                    <div class="space-y-4">
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Schema Type</label>
                            <select name="schema_type" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">
                                <option value="">None</option>
                                @foreach(['Product', 'WebPage', 'Organization', 'LocalBusiness', 'Service', 'BreadcrumbList', 'FAQPage', 'Article'] as $type)
                                <option value="{{ $type }}" {{ ($seoMeta->schema_type ?? '') === $type ? 'selected' : '' }}>{{ $type }}</option>
                                @endforeach
                            </select>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Schema Markup (JSON)</label>
                            <textarea name="schema_markup" rows="5" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 font-mono text-xs text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('schema_markup', is_array($seoMeta->schema_markup) ? json_encode($seoMeta->schema_markup, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) : ($seoMeta->schema_markup ?? '')) }}</textarea>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Hreflang (JSON)</label>
                            <textarea name="hreflang" rows="3" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 font-mono text-xs text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('hreflang', is_array($seoMeta->hreflang) ? json_encode($seoMeta->hreflang, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) : ($seoMeta->hreflang ?? '')) }}</textarea>
                        </div>
                        <div>
                            <label class="mb-1 block text-sm font-medium text-[#94A3B8]">Internal Notes</label>
                            <textarea name="notes" rows="2" class="w-full rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3] focus:border-[#3B82F6] focus:outline-none">{{ old('notes', $seoMeta->notes) }}</textarea>
                        </div>
                        <div class="flex items-center gap-3">
                            <label class="relative inline-flex cursor-pointer items-center">
                                <input type="hidden" name="status" value="0">
                                <input type="checkbox" name="status" value="1" {{ $seoMeta->status ? 'checked' : '' }} class="peer sr-only">
                                <div class="h-6 w-11 rounded-full bg-[#232A36] after:absolute after:left-[2px] after:top-[2px] after:h-5 after:w-5 after:rounded-full after:bg-[#94A3B8] after:transition-all peer-checked:bg-[#3B82F6] peer-checked:after:translate-x-full peer-checked:after:bg-white"></div>
                            </label>
                            <span class="text-sm text-[#94A3B8]">Active</span>
                        </div>
                    </div>
                </x-card>
            </div>

            {{-- Preview --}}
            @if($seoMeta->meta_title || $seoMeta->meta_description)
            <x-card class="mt-6 p-6">
                <h3 class="mb-4 text-lg font-semibold text-[#E6EDF3]">Preview</h3>
                <div class="rounded-xl border border-[#232A36] bg-[#161B22] p-4">
                    <p class="text-lg font-medium text-[#3B82F6]">{{ $seoMeta->meta_title }}</p>
                    <p class="mt-1 text-sm text-[#22C55E]">{{ url('/') }}/...</p>
                    <p class="mt-1 text-sm text-[#94A3B8]">{{ $seoMeta->meta_description }}</p>
                </div>
            </x-card>
            @endif

            <div class="mt-6 flex justify-end gap-3">
                <a href="{{ admin_route('seo.index') }}" class="rounded-xl border border-[#232A36] px-6 py-2.5 text-sm font-medium text-[#94A3B8] hover:bg-[#1C2333]">Cancel</a>
                <button type="submit" class="rounded-xl bg-[#3B82F6] px-6 py-2.5 text-sm font-medium text-white hover:bg-[#2563EB]">
                    <i class="fas fa-save mr-1"></i> Save Changes
                </button>
            </div>
        </form>
    </div>
</x-layouts.app>
