<x-layouts.app title="SEO Management">
    <div class="space-y-6">
        <div class="flex items-center justify-between">
            <h1 class="text-2xl font-bold text-[#E6EDF3]">SEO Management</h1>
            <div class="flex gap-2">
                <a href="{{ admin_route('seo.auto-generate') }}" onclick="return confirm('Run auto SEO generation? This will overwrite template-based fields.')" class="inline-flex items-center gap-2 rounded-xl bg-[#22C55E] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#16A34A]">
                    <i class="fas fa-magic"></i> Auto-Generate
                </a>
            </div>
        </div>

        {{-- Stats Cards --}}
        <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#E6EDF3]">{{ $counts['total'] }}</p>
                <p class="text-xs text-[#94A3B8]">Total</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#3B82F6]">{{ $counts['products'] }}</p>
                <p class="text-xs text-[#94A3B8]">Products</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#8B5CF6]">{{ $counts['projects'] }}</p>
                <p class="text-xs text-[#94A3B8]">Projects</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#F59E0B]">{{ $counts['categories'] }}</p>
                <p class="text-xs text-[#94A3B8]">Categories</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#22C55E]">{{ $counts['auto'] }}</p>
                <p class="text-xs text-[#94A3B8]">Auto</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#EF4444]">{{ $counts['manual'] }}</p>
                <p class="text-xs text-[#94A3B8]">Manual</p>
            </x-card>
        </div>

        {{-- Filters --}}
        <form method="GET" class="flex flex-wrap gap-3">
            <select name="type" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                <option value="">All Types</option>
                <option value="App\Models\Product" {{ request('type') === 'App\Models\Product' ? 'selected' : '' }}>Products</option>
                <option value="App\Models\WebsiteProject" {{ request('type') === 'App\Models\WebsiteProject' ? 'selected' : '' }}>Projects</option>
                <option value="App\Models\WebsiteCategory" {{ request('type') === 'App\Models\WebsiteCategory' ? 'selected' : '' }}>Categories</option>
            </select>
            <select name="autogenerated" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                <option value="">All Sources</option>
                <option value="yes" {{ request('autogenerated') === 'yes' ? 'selected' : '' }}>Auto-Generated</option>
                <option value="no" {{ request('autogenerated') === 'no' ? 'selected' : '' }}>Manual</option>
            </select>
            <select name="status" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                <option value="">All Status</option>
                <option value="active" {{ request('status') === 'active' ? 'selected' : '' }}>Active</option>
                <option value="inactive" {{ request('status') === 'inactive' ? 'selected' : '' }}>Inactive</option>
            </select>
            <button type="submit" class="rounded-xl bg-[#3B82F6] px-4 py-2 text-sm font-medium text-white">Filter</button>
            <a href="{{ admin_route('seo.index') }}" class="rounded-xl border border-[#232A36] px-4 py-2 text-sm text-[#94A3B8]">Reset</a>
        </form>

        {{-- Table --}}
        <x-card class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead>
                    <tr class="border-b border-[#232A36] text-left text-[#94A3B8]">
                        <th class="pb-3 font-medium">Type</th>
                        <th class="pb-3 font-medium">Name</th>
                        <th class="pb-3 font-medium">Meta Title</th>
                        <th class="pb-3 font-medium">Meta Description</th>
                        <th class="pb-3 font-medium">Source</th>
                        <th class="pb-3 font-medium">Status</th>
                        <th class="pb-3 font-medium text-right">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    @forelse($seoMetas as $seo)
                    <tr class="border-b border-[#232A36]/50 hover:bg-[#1C2333]">
                        <td class="py-3 text-[#E6EDF3]">
                            <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium
                                {{ class_basename($seo->seoable_type) === 'Product' ? 'bg-[#3B82F6]/10 text-[#3B82F6]' :
                                   (class_basename($seo->seoable_type) === 'WebsiteProject' ? 'bg-[#8B5CF6]/10 text-[#8B5CF6]' : 'bg-[#F59E0B]/10 text-[#F59E0B]') }}">
                                {{ class_basename($seo->seoable_type) }}
                            </span>
                        </td>
                        <td class="py-3 text-[#E6EDF3]">{{ $seo->seoable?->name ?? $seo->seoable?->title ?? '—' }}</td>
                        <td class="py-3 text-[#94A3B8] max-w-[200px] truncate">{{ $seo->meta_title ?? '—' }}</td>
                        <td class="py-3 text-[#94A3B8] max-w-[250px] truncate">{{ $seo->meta_description ?? '—' }}</td>
                        <td class="py-3">
                            <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium {{ $seo->is_autogenerated ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#EF4444]/10 text-[#EF4444]' }}">
                                {{ $seo->is_autogenerated ? 'Auto' : 'Manual' }}
                            </span>
                        </td>
                        <td class="py-3">
                            <span class="inline-flex items-center rounded-full px-2 py-0.5 text-xs font-medium {{ $seo->status ? 'bg-[#22C55E]/10 text-[#22C55E]' : 'bg-[#6B7280]/10 text-[#6B7280]' }}">
                                {{ $seo->status ? 'Active' : 'Inactive' }}
                            </span>
                        </td>
                        <td class="py-3 text-right">
                            <div class="flex items-center justify-end gap-2">
                                <a href="{{ admin_route('seo.edit', $seo->id) }}" class="rounded-lg bg-[#3B82F6]/10 px-3 py-1.5 text-xs font-medium text-[#3B82F6] hover:bg-[#3B82F6]/20">
                                    <i class="fas fa-edit"></i> Edit
                                </a>
                                @if($seo->is_autogenerated)
                                <a href="{{ admin_route('seo.reset-template', $seo->id) }}" onclick="return confirm('Reset to template?')" class="rounded-lg bg-[#F59E0B]/10 px-3 py-1.5 text-xs font-medium text-[#F59E0B] hover:bg-[#F59E0B]/20">
                                    <i class="fas fa-undo"></i>
                                </a>
                                @endif
                                <form action="{{ admin_route('seo.destroy', $seo->id) }}" method="POST" class="inline" onsubmit="return confirm('Delete this SEO meta?')">
                                    @csrf @method('DELETE')
                                    <button type="submit" class="rounded-lg bg-[#EF4444]/10 px-3 py-1.5 text-xs font-medium text-[#EF4444] hover:bg-[#EF4444]/20">
                                        <i class="fas fa-trash"></i>
                                    </button>
                                </form>
                            </div>
                        </td>
                    </tr>
                    @empty
                    <tr>
                        <td colspan="7" class="py-12 text-center text-[#94A3B8]">
                            <i class="fas fa-search mb-3 text-3xl text-[#232A36]"></i>
                            <p>No SEO records found.</p>
                        </td>
                    </tr>
                    @endforelse
                </tbody>
            </table>
        </x-card>

        <div class="mt-4">
            {{ $seoMetas->withQueryString()->links('components.pagination') }}
        </div>
    </div>
</x-layouts.app>
