<x-layouts.app title="SEO Management">
    <div class="space-y-6" x-data="seoManagement()">
        <div class="flex items-center justify-between">
            <h1 class="text-2xl font-bold text-[#E6EDF3]">SEO Management</h1>
            <div class="flex gap-2">
                <form method="POST" action="{{ admin_route('seo.auto-generate') }}" onsubmit="return confirm('Run auto SEO generation? This will overwrite template-based fields.')" class="inline">
                    @csrf
                    <button type="submit" class="inline-flex items-center gap-2 rounded-xl bg-[#22C55E] px-4 py-2.5 text-sm font-medium text-white hover:bg-[#16A34A]">
                    <i class="fas fa-magic"></i> Auto-Generate
                </button></form>
            </div>
        </div>

        {{-- Stats Cards --}}
        <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-6">
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#E6EDF3]">{{ $counts['total'] }}</p>
                <p class="text-xs text-[#94A3B8]">Total</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#3B82F6]">{{ $counts['products'] }}</p>
                <p class="text-xs text-[#94A3B8]">Products</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#8B5CF6]">{{ $counts['projects'] }}</p>
                <p class="text-xs text-[#94A3B8]">Products</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#F59E0B]">{{ $counts['categories'] }}</p>
                <p class="text-xs text-[#94A3B8]">Categories</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#22C55E]">{{ $counts['auto'] }}</p>
                <p class="text-xs text-[#94A3B8]">Auto</p>
            </x-card>
            <x-card class="p-4 text-center">
                <p class="text-2xl font-bold text-[#EF4444]">{{ $counts['manual'] }}</p>
                <p class="text-xs text-[#94A3B8]">Manual</p>
            </x-card>
        </div>

        {{-- Filters --}}
        <x-card>
            <div class="flex flex-wrap gap-3">
                <select x-model="filters.type" @change="fetchSeo()" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                    <option value="">All Types</option>
                    <option value="App\Models\Product">Products</option>
                    <option value="App\Models\WebsiteProject">Projects</option>
                    <option value="App\Models\WebsiteCategory">Categories</option>
                </select>
                <select x-model="filters.autogenerated" @change="fetchSeo()" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                    <option value="">All Sources</option>
                    <option value="yes">Auto-Generated</option>
                    <option value="no">Manual</option>
                </select>
                <select x-model="filters.status" @change="fetchSeo()" class="rounded-xl border border-[#232A36] bg-[#161B22] px-3 py-2 text-sm text-[#E6EDF3]">
                    <option value="">All Status</option>
                    <option value="active">Active</option>
                    <option value="inactive">Inactive</option>
                </select>
                <button @click="resetFilters()" class="rounded-xl border border-[#232A36] px-4 py-2 text-sm text-[#94A3B8] hover:bg-[#1C2333]">Reset</button>
            </div>
        </x-card>

        {{-- Table --}}
        <div id="seoContainer" x-html="tableHtml" class="space-y-4">
            @include('seo._table')
        </div>
    </div>

    <script>
        function seoManagement() {
            return {
                filters: {
                    type: '',
                    autogenerated: '',
                    status: '',
                },
                page: 1,
                tableHtml: '',
                loading: false,

                init() {
                    this.fetchSeo();
                    window.seoGoToPage = (p) => { this.page = p; this.fetchSeo(); };
                },

                fetchSeo() {
                    if (this.loading) return;
                    this.loading = true;

                    const params = new URLSearchParams();
                    Object.entries(this.filters).forEach(([k, v]) => { if (v) params.append(k, v); });
                    params.append('page', this.page);

                    fetch('{{ admin_route('seo.index') }}?' + params.toString(), {
                        headers: { 'X-Requested-With': 'XMLHttpRequest' }
                    })
                    .then(r => r.text())
                    .then(html => {
                        this.tableHtml = html;
                        this.loading = false;
                    })
                    .catch(() => { this.loading = false; });
                },

                resetFilters() {
                    this.filters = { type: '', autogenerated: '', status: '' };
                    this.page = 1;
                    this.fetchSeo();
                },
            };
        }
    </script>
</x-layouts.app>
