<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('seo_meta', function (Blueprint $table) {
            $table->id();
            $table->morphs('seoable');

            $table->string('meta_title', 255)->nullable();
            $table->text('meta_description')->nullable();
            $table->json('focus_keywords')->nullable();
            $table->string('og_title', 255)->nullable();
            $table->text('og_description')->nullable();
            $table->string('og_image', 500)->nullable();
            $table->string('og_url', 500)->nullable();
            $table->string('twitter_title', 255)->nullable();
            $table->string('twitter_description', 200)->nullable();
            $table->string('twitter_image', 500)->nullable();
            $table->string('canonical_url', 500)->nullable();
            $table->string('robots', 20)->default('index,follow');
            $table->json('hreflang')->nullable();
            $table->string('schema_type', 50)->nullable();
            $table->json('schema_markup')->nullable();
            $table->boolean('is_autogenerated')->default(true);
            $table->text('notes')->nullable();
            $table->boolean('status')->default(true);

            $table->unique(['seoable_type', 'seoable_id']);
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('seo_meta');
    }
};
