<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('seo_media', function (Blueprint $table) {
            $table->id();
            $table->morphs('imageable');
            $table->string('image_path', 500);
            $table->text('alt_text')->nullable();
            $table->string('image_title', 200)->nullable();
            $table->text('image_description')->nullable();
            $table->boolean('is_autogenerated')->default(true);
            $table->boolean('needs_review')->default(false);
            $table->timestamps();
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('seo_media');
    }
};
