<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\MorphTo;

class SeoMedia extends Model
{
    protected $table = 'seo_media';

    protected $fillable = [
        'imageable_type', 'imageable_id',
        'image_path', 'alt_text', 'image_title',
        'image_description', 'is_autogenerated', 'needs_review',
    ];

    protected function casts(): array
    {
        return [
            'is_autogenerated' => 'boolean',
            'needs_review' => 'boolean',
        ];
    }

    public function imageable(): MorphTo
    {
        return $this->morphTo();
    }

    public function scopeNeedsReview($query)
    {
        return $query->where('needs_review', true);
    }
}
