<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class SeoMeta extends Model
{
    use HasFactory;

    protected $table = 'seo_meta';

    protected $fillable = [
        'seoable_type',
        'seoable_id',
        'meta_title',
        'meta_description',
        'focus_keywords',
        'og_title',
        'og_description',
        'og_image',
        'og_url',
        'twitter_title',
        'twitter_description',
        'twitter_image',
        'canonical_url',
        'robots',
        'hreflang',
        'schema_type',
        'schema_markup',
        'is_autogenerated',
        'notes',
        'status',
    ];

    protected $casts = [
        'focus_keywords' => 'array',
        'hreflang' => 'array',
        'schema_markup' => 'array',
        'is_autogenerated' => 'boolean',
        'status' => 'boolean',
    ];

    public function seoable(): \Illuminate\Database\Eloquent\Relations\MorphTo
    {
        return $this->morphTo();
    }
}
