<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\PendingOrderTransaction;
use App\Models\Product;
use App\Models\SeoMeta;
use App\Models\StockTransaction;
use App\Models\WorkLog;
use Illuminate\Http\Request;

class AutomationController extends Controller
{
    public function __invoke(Request $request)
    {
        $auditLogs = WorkLog::where('module', 'Audit')
            ->latest()
            ->take(10)
            ->get()
            ->map(function ($log) {
                preg_match_all('/\[([A-Z0-9]+)\]/', $log->description ?? '', $checks);
                $issues = substr_count($log->action, 'issue');
                preg_match('/auto-fixed: (\d+)/', $log->action, $fixed);
                return [
                    'id' => $log->id,
                    'ran_at' => $log->created_at,
                    'summary' => $log->action,
                    'details' => $log->description,
                    'checks' => $checks[1] ?? [],
                    'issues' => $issues,
                    'fixed' => (int) ($fixed[1] ?? 0),
                ];
            });

        $schedulerFile = base_path('routes/console.php');
        $schedulerTasks = $this->parseSchedulerTasks($schedulerFile);

        $schedulerStats = $this->getSchedulerStats($schedulerTasks);

        $pendingTransactions = PendingOrderTransaction::where('status', 'pending')->count();
        $pendingAmount = PendingOrderTransaction::where('status', 'pending')->sum('total_amount');

        $ordersByStatus = Order::selectRaw("
                status,
                COUNT(*) as count,
                COALESCE(SUM(total_amount), 0) as total,
                COALESCE(SUM(pending_payment), 0) as pending
            ")
            ->groupBy('status')
            ->get()
            ->keyBy('status');

        $autoRestoredCount = Order::whereNotNull('auto_restored_at')->count();
        $autoSeoCount = SeoMeta::where('is_autogenerated', true)->count();
        $observerStats = $this->getObserverStats();

        $stockCheckLogs = WorkLog::where(function ($q) {
                $q->where('action', 'like', '%Auto Out of Stock%')
                  ->orWhere('action', 'like', '%Auto-Restored%');
            })
            ->latest()
            ->take(10)
            ->get()
            ->map(fn($l) => [
                'action' => $l->action,
                'order_ref' => $l->reference_id,
                'ran_at' => $l->created_at,
            ]);

        $logFiles = [
            'audit' => $this->getLogFileInfo(storage_path('logs/audit.log')),
            'cleanup' => $this->getLogFileInfo(storage_path('logs/cleanup.log')),
            'laravel' => $this->getLogFileInfo(storage_path('logs/laravel.log')),
        ];

        $clientPolls = [
            ['name' => 'Stock Auto-Checker', 'interval' => '30s', 'location' => 'Orders Index, Create, Edit'],
            ['name' => 'KPI Cards Refresh', 'interval' => '60s', 'location' => 'Dashboard'],
            ['name' => 'Orders Table Refresh', 'interval' => '60s', 'location' => 'Orders Index'],
            ['name' => 'Stock Table Refresh', 'interval' => '60s', 'location' => 'Stock Management'],
            ['name' => 'Notifications Poll', 'interval' => '30s', 'location' => 'Global Layout'],
        ];

        $onDemandActions = [
            ['name' => 'Run Audit', 'route' => 'monitoring.run-audit', 'method' => 'POST', 'icon' => 'play'],
            ['name' => 'Auto-Generate SEO', 'route' => 'seo.auto-generate', 'method' => 'POST', 'icon' => 'magic'],
        ];

        return view('monitoring.automation', compact(
            'auditLogs',
            'schedulerTasks',
            'schedulerStats',
            'pendingTransactions',
            'pendingAmount',
            'ordersByStatus',
            'autoRestoredCount',
            'autoSeoCount',
            'observerStats',
            'stockCheckLogs',
            'logFiles',
            'clientPolls',
            'onDemandActions',
        ));
    }

    private function parseSchedulerTasks(string $file): array
    {
        if (!file_exists($file)) return [];

        $content = file_get_contents($file);
        preg_match_all('/Schedule::command\(([^,]+)(?:, ([^)]+))?\)->([\w:]+)\(\)/', $content, $matches, PREG_SET_ORDER);

        $tasks = [];
        foreach ($matches as $m) {
            $command = trim($m[1], "'\" ");
            $args = isset($m[2]) ? trim($m[2], "'\" []") : '';
            $freq = $m[3] ?? 'unknown';
            $name = class_basename(str_replace('::class', '', $command));
            $tasks[] = [
                'name' => $name ?: $command,
                'command' => str_replace('::class', '', $command),
                'args' => $args,
                'frequency' => $this->freqLabel($freq),
                'type' => $this->freqType($freq),
            ];
        }
        return $tasks;
    }

    private function freqLabel(string $freq): string
    {
        return match ($freq) {
            'everyFiveMinutes' => 'Every 5 min',
            'everyTenMinutes' => 'Every 10 min',
            'everyFifteenMinutes' => 'Every 15 min',
            'everyThirtyMinutes' => 'Every 30 min',
            'hourly' => 'Hourly',
            'daily' => 'Daily',
            'weekly' => 'Weekly',
            'monthly' => 'Monthly',
            default => $freq,
        };
    }

    private function freqType(string $freq): string
    {
        return match ($freq) {
            'everyFiveMinutes', 'everyTenMinutes', 'everyFifteenMinutes', 'everyThirtyMinutes' => 'frequent',
            'hourly' => 'hourly',
            'daily', 'weekly', 'monthly' => 'slow',
            default => 'slow',
        };
    }

    private function getSchedulerStats(array $tasks): array
    {
        $count = count($tasks);
        $frequent = collect($tasks)->where('type', 'frequent')->count();
        $hourly = collect($tasks)->where('type', 'hourly')->count();
        $slow = collect($tasks)->where('type', 'slow')->count();
        return compact('count', 'frequent', 'hourly', 'slow');
    }

    private function getObserverStats(): array
    {
        $autoProducts = Product::whereHas('seoMeta', fn($q) => $q->where('is_autogenerated', true))->count();
        $totalProducts = Product::count();
        $totalSeo = SeoMeta::count();

        return [
            'auto_products' => $autoProducts,
            'total_products' => $totalProducts,
            'total_seo' => $totalSeo,
        ];
    }

    private function getLogFileInfo(string $path): array
    {
        if (!file_exists($path)) {
            return ['exists' => false, 'size' => 0, 'modified' => null];
        }
        return [
            'exists' => true,
            'size' => filesize($path),
            'size_formatted' => $this->formatBytes(filesize($path)),
            'modified' => date('Y-m-d H:i:s', filemtime($path)),
        ];
    }

    private function formatBytes(int $bytes): string
    {
        if ($bytes >= 1048576) return round($bytes / 1048576, 1) . ' MB';
        if ($bytes >= 1024) return round($bytes / 1024, 1) . ' KB';
        return $bytes . ' B';
    }
}
