<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Order;
use App\Models\PendingOrderTransaction;
use App\Models\Product;
use App\Models\SeoMeta;
use App\Models\WorkLog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class AutomationController extends Controller
{
    public function __invoke(Request $request)
    {
        $auditLogs = WorkLog::where('module', 'Audit')
            ->latest()
            ->take(10)
            ->get()
            ->map(function ($log) {
                preg_match_all('/\[([A-Z0-9]+)\]/', $log->description ?? '', $checks);
                $issues = substr_count($log->action, 'issue');
                preg_match('/auto-fixed: (\d+)/', $log->action, $fixed);
                return [
                    'id' => $log->id,
                    'ran_at' => $log->created_at,
                    'summary' => $log->action,
                    'details' => $log->description,
                    'checks' => $checks[1] ?? [],
                    'issues' => $issues,
                    'fixed' => (int) ($fixed[1] ?? 0),
                ];
            });

        $schedulerFile = base_path('routes/console.php');
        $schedulerTasks = $this->parseSchedulerTasks($schedulerFile);

        $schedulerStats = $this->getSchedulerStats($schedulerTasks);

        $pendingTransactions = PendingOrderTransaction::where('status', 'pending')->count();
        $pendingAmount = PendingOrderTransaction::where('status', 'pending')->sum('total_amount');

        $ordersByStatus = Order::selectRaw("
                status,
                COUNT(*) as count,
                COALESCE(SUM(total_amount), 0) as total,
                COALESCE(SUM(pending_payment), 0) as pending
            ")
            ->groupBy('status')
            ->get()
            ->keyBy('status');

        $autoRestoredCount = Order::whereNotNull('auto_restored_at')->count();
        $autoSeoCount = SeoMeta::where('is_autogenerated', true)->count();
        $observerStats = $this->getObserverStats();

        $stockCheckLogs = WorkLog::where(function ($q) {
                $q->where('action', 'like', '%Auto Out of Stock%')
                  ->orWhere('action', 'like', '%Auto-Restored%');
            })
            ->latest()
            ->take(10)
            ->get()
            ->map(fn($l) => [
                'action' => $l->action,
                'order_ref' => $l->reference_id,
                'ran_at' => $l->created_at,
            ]);

        $logFiles = [
            'audit' => $this->getLogFileInfo(storage_path('logs/audit.log')),
            'cleanup' => $this->getLogFileInfo(storage_path('logs/cleanup.log')),
            'laravel' => $this->getLogFileInfo(storage_path('logs/laravel.log')),
        ];

        $clientPolls = [
            ['key' => 'dashboard-clock', 'name' => 'Dashboard Clock', 'default_interval' => 60, 'page' => 'Dashboard', 'description' => 'Updates the dashboard datetime display'],
            ['key' => 'dashboard-kpi', 'name' => 'KPI Cards Refresh', 'default_interval' => 60, 'page' => 'Dashboard', 'description' => 'Refreshes KPI cards with latest statistics'],
            ['key' => 'orders-reload', 'name' => 'Orders Table Refresh', 'default_interval' => 60, 'page' => 'Orders Index', 'description' => 'Fetches latest orders and drafts list'],
            ['key' => 'orders-stock-check', 'name' => 'Stock Auto-Checker', 'default_interval' => 30, 'page' => 'Orders Index', 'description' => 'Checks for out-of-stock orders and auto-restores'],
            ['key' => 'notification-bell', 'name' => 'Notifications Poll', 'default_interval' => 30, 'page' => 'Global Layout', 'description' => 'Polls unread notification count'],
            ['key' => 'stock-table', 'name' => 'Stock Table Refresh', 'default_interval' => 60, 'page' => 'Stock Management', 'description' => 'Refreshes the stock management table'],
            ['key' => 'order-create-stock', 'name' => 'Order Create Stock', 'default_interval' => 30, 'page' => 'Order Create', 'description' => 'Checks stock availability during order creation'],
            ['key' => 'order-edit-stock', 'name' => 'Order Edit Stock', 'default_interval' => 30, 'page' => 'Order Edit', 'description' => 'Checks stock availability during order editing'],
        ];

        $onDemandActions = [
            ['name' => 'Run Audit', 'route' => 'monitoring.run-audit', 'method' => 'POST', 'icon' => 'play'],
            ['name' => 'Auto-Generate SEO', 'route' => 'seo.auto-generate', 'method' => 'POST', 'icon' => 'magic'],
        ];

        $pollTracker = DB::table('tracker')->where('type', 'poll')->get()->keyBy('key');

        return view('monitoring.automation', compact(
            'auditLogs',
            'schedulerTasks',
            'schedulerStats',
            'pendingTransactions',
            'pendingAmount',
            'ordersByStatus',
            'autoRestoredCount',
            'autoSeoCount',
            'observerStats',
            'stockCheckLogs',
            'logFiles',
            'clientPolls',
            'onDemandActions',
            'pollTracker',
        ));
    }

    private function parseSchedulerTasks(string $file): array
    {
        if (!file_exists($file)) return [];

        $content = file_get_contents($file);
        preg_match_all('/Schedule::command\(([^)]+)\)->([\w:]+)\(\)/', $content, $matches, PREG_SET_ORDER);

        $taskMeta = [
            'CleanOldData' => ['name' => 'Clean Old Data', 'description' => 'Removes old records from the database that are no longer needed, keeping the system fast and clean.'],
            'CleanOldDrafts' => ['name' => 'Clean Old Drafts', 'description' => 'Deletes draft orders that were never completed, preventing clutter in the orders list.'],
            'PurgeOldFinanceData' => ['name' => 'Purge Old Finance Data', 'description' => 'Removes old financial records to keep the finance section lightweight and organized.'],
            'SeoAutoGenerateCommand' => ['name' => 'Auto-Generate SEO', 'description' => 'Creates SEO-friendly titles and descriptions for products, categories, and projects automatically.'],
            'CleanOldPdfDownloads' => ['name' => 'Clean Old PDFs', 'description' => 'Removes old downloaded PDF files to free up storage space on the server.'],
            'CleanReadNotifications' => ['name' => 'Clean Read Notifications', 'description' => 'Deletes notifications that have already been read, keeping the notification panel tidy.'],
            'AuditSystemConsistency' => ['name' => 'System Consistency Check', 'description' => 'Scans the entire system for data mismatches, missing records, or inconsistencies and fixes them automatically.'],
            'app:clean-pending-images' => ['name' => 'Clean Pending Images', 'description' => 'Removes temporary or pending image files that are no longer needed.'],
            'clean-pending-images' => ['name' => 'Clean Pending Images', 'description' => 'Removes temporary or pending image files that are no longer needed.'],
        ];

        $commandMap = [
            'CleanOldData' => 'app:clean-old-data',
            'CleanOldDrafts' => 'app:clean-old-drafts',
            'PurgeOldFinanceData' => 'finance:purge-old',
            'SeoAutoGenerateCommand' => 'seo:auto-generate',
            'CleanOldPdfDownloads' => 'app:clean-old-pdf-downloads',
            'CleanReadNotifications' => 'app:clean-read-notifications',
            'AuditSystemConsistency' => 'app:audit-consistency',
        ];

        $taskTracker = DB::table('tracker')->where('type', 'task')->get()->keyBy('key');

        $tasks = [];
        foreach ($matches as $m) {
            $raw = trim($m[1], "'\" ");
            $freq = $m[2] ?? 'unknown';
            $baseName = class_basename(str_replace('::class', '', $raw));
            $meta = $taskMeta[$baseName] ?? $taskMeta[$raw] ?? ['name' => $baseName ?: $raw, 'description' => 'System maintenance task.'];
            $commandSignature = $commandMap[$baseName] ?? (str_starts_with($raw, 'app:') ? $raw : $baseName);

            $tracked = $taskTracker[$commandSignature] ?? null;
            $lastRunAt = $tracked ? $tracked->last_run_at : null;
            $runCount = $tracked ? $tracked->run_count : 0;

            $tasks[] = [
                'name' => $meta['name'],
                'description' => $meta['description'],
                'command' => $raw,
                'command_signature' => $commandSignature,
                'frequency' => $this->freqLabel($freq),
                'type' => $this->freqType($freq),
                'last_run_at' => $lastRunAt ? [
                    'timestamp' => $lastRunAt instanceof \Carbon\Carbon ? $lastRunAt->timestamp : strtotime($lastRunAt),
                    'formatted' => $lastRunAt instanceof \Carbon\Carbon ? $lastRunAt->format('H:i:s') : date('H:i:s', strtotime($lastRunAt)),
                    'diff' => $lastRunAt instanceof \Carbon\Carbon ? $lastRunAt->diffForHumans() : \Carbon\Carbon::parse($lastRunAt)->diffForHumans(),
                ] : null,
                'run_count' => $runCount,
            ];
        }
        return $tasks;
    }

    private function getLogForCommand(string $signature): ?string
    {
        $logs = [
            'app:audit-consistency' => 'audit.log',
            'app:clean-old-data' => 'cleanup.log',
        ];
        $f = $logs[$signature] ?? null;
        return $f && file_exists(storage_path("logs/$f")) ? storage_path("logs/$f") : null;
    }

    private function freqLabel(string $freq): string
    {
        return match ($freq) {
            'everyFiveMinutes' => 'Every 5 min',
            'everyTenMinutes' => 'Every 10 min',
            'everyFifteenMinutes' => 'Every 15 min',
            'everyThirtyMinutes' => 'Every 30 min',
            'hourly' => 'Hourly',
            'daily' => 'Daily',
            'weekly' => 'Weekly',
            'monthly' => 'Monthly',
            default => $freq,
        };
    }

    private function freqType(string $freq): string
    {
        return match ($freq) {
            'everyFiveMinutes', 'everyTenMinutes', 'everyFifteenMinutes', 'everyThirtyMinutes' => 'frequent',
            'hourly' => 'hourly',
            'daily', 'weekly', 'monthly' => 'slow',
            default => 'slow',
        };
    }

    private function getSchedulerStats(array $tasks): array
    {
        $count = count($tasks);
        $frequent = collect($tasks)->where('type', 'frequent')->count();
        $hourly = collect($tasks)->where('type', 'hourly')->count();
        $slow = collect($tasks)->where('type', 'slow')->count();
        return compact('count', 'frequent', 'hourly', 'slow');
    }

    private function getObserverStats(): array
    {
        $autoProducts = Product::whereHas('seoMeta', fn($q) => $q->where('is_autogenerated', true))->count();
        $totalProducts = Product::count();
        $totalSeo = SeoMeta::count();

        return [
            'auto_products' => $autoProducts,
            'total_products' => $totalProducts,
            'total_seo' => $totalSeo,
        ];
    }

    private function getLogFileInfo(string $path): array
    {
        if (!file_exists($path)) {
            return ['exists' => false, 'size' => 0, 'modified' => null];
        }
        return [
            'exists' => true,
            'size' => filesize($path),
            'size_formatted' => $this->formatBytes(filesize($path)),
            'modified' => date('Y-m-d H:i:s', filemtime($path)),
        ];
    }

    private function formatBytes(int $bytes): string
    {
        if ($bytes >= 1048576) return round($bytes / 1048576, 1) . ' MB';
        if ($bytes >= 1024) return round($bytes / 1024, 1) . ' KB';
        return $bytes . ' B';
    }
}
