<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\SeoMeta;
use App\Models\WebsiteCategory;
use App\Models\WebsiteProject;
use App\Services\SeoService;
use App\Services\WorkLogService;
use Illuminate\Http\Request;

class SeoController extends Controller
{
    protected SeoService $seoService;
    protected WorkLogService $workLogService;

    public function __construct(SeoService $seoService, WorkLogService $workLogService)
    {
        $this->seoService = $seoService;
        $this->workLogService = $workLogService;
    }

    public function index(Request $request)
    {
        $query = SeoMeta::with('seoable');

        if ($request->filled('type')) {
            $query->where('seoable_type', $request->type);
        }
        if ($request->filled('status')) {
            $query->where('status', $request->status === 'active');
        }
        if ($request->filled('autogenerated')) {
            $query->where('is_autogenerated', $request->autogenerated === 'yes');
        }

        $seoMetas = $query->latest()->paginate(20);

        if ($request->ajax()) {
            return view('seo._table', compact('seoMetas'));
        }

        $counts = [
            'total' => SeoMeta::count(),
            'products' => SeoMeta::where('seoable_type', Product::class)->count(),
            'projects' => SeoMeta::where('seoable_type', WebsiteProject::class)->count(),
            'categories' => SeoMeta::where('seoable_type', WebsiteCategory::class)->count(),
            'auto' => SeoMeta::where('is_autogenerated', true)->count(),
            'manual' => SeoMeta::where('is_autogenerated', false)->count(),
        ];

        return view('seo.index', compact('seoMetas', 'counts'));
    }

    public function edit(string $role, SeoMeta $seoMeta)
    {
        $seoMeta->load('seoable');

        $editableFields = $this->getEditableFields();

        return view('seo.edit', compact('seoMeta', 'editableFields'));
    }

    public function update(Request $request, string $role, SeoMeta $seoMeta)
    {
        $validated = $request->validate([
            'meta_title' => 'nullable|string|max:70',
            'meta_description' => 'nullable|string|max:500',
            'focus_keywords' => 'nullable|string',
            'og_title' => 'nullable|string|max:70',
            'og_description' => 'nullable|string|max:200',
            'og_image' => 'nullable|string|max:500',
            'og_url' => 'nullable|url|max:500',
            'twitter_title' => 'nullable|string|max:70',
            'twitter_description' => 'nullable|string|max:200',
            'twitter_image' => 'nullable|string|max:500',
            'canonical_url' => 'nullable|url|max:500',
            'robots' => 'nullable|string|max:20',
            'hreflang' => 'nullable|string',
            'schema_type' => 'nullable|string|max:50',
            'schema_markup' => 'nullable|string',
            'notes' => 'nullable|string',
            'status' => 'nullable|boolean',
        ]);

        if (isset($validated['focus_keywords']) && is_string($validated['focus_keywords'])) {
            $validated['focus_keywords'] = $this->seoService->parseKeywords($validated['focus_keywords']);
        }

        if (isset($validated['hreflang']) && is_string($validated['hreflang'])) {
            $validated['hreflang'] = json_decode($validated['hreflang'], true) ?? [];
        }

        if (isset($validated['schema_markup']) && is_string($validated['schema_markup'])) {
            $validated['schema_markup'] = json_decode($validated['schema_markup'], true) ?? null;
        }

        if (isset($validated['status'])) {
            $validated['status'] = (bool) $validated['status'];
        }

        $validated['is_autogenerated'] = false;

        $seoMeta->update($validated);

        $this->workLogService->log('SEO Updated', 'seo', $seoMeta->id, "SEO meta for {$seoMeta->seoable_type} #{$seoMeta->seoable_id} updated");

        return redirect(admin_route('seo.edit', $seoMeta->id))
            ->with('success', 'SEO meta updated successfully.');
    }

    public function destroy(string $role, SeoMeta $seoMeta)
    {
        $seoMeta->delete();

        $this->workLogService->log('SEO Deleted', 'seo', $seoMeta->id, "SEO meta #{$seoMeta->id} deleted");

        return redirect(admin_route('seo.index'))
            ->with('success', 'SEO meta deleted.');
    }

    public function resetTemplate(string $role, SeoMeta $seoMeta)
    {
        $seoMeta->load('seoable');
        $this->seoService->applyTemplate($seoMeta->seoable);

        $this->workLogService->log('SEO Reset', 'seo', $seoMeta->id, "SEO meta for {$seoMeta->seoable_type} #{$seoMeta->seoable_id} reset to template");

        return redirect(admin_route('seo.edit', $seoMeta->id))
            ->with('success', 'SEO meta reset to template.');
    }

    public function autoGenerate(string $role)
    {
        $exitCode = \Artisan::call('seo:auto-generate', ['--force' => true]);
        $output = \Artisan::output();

        $this->workLogService->log('SEO Auto Generated', 'seo', null, 'Auto SEO generation completed');

        return redirect(admin_route('seo.index'))
            ->with('success', 'Auto SEO generation completed. Check the command output for details.');
    }

    protected function getEditableFields(): array
    {
        $base = [
            'meta_title' => ['label' => 'Meta Title', 'type' => 'text', 'max' => 70],
            'meta_description' => ['label' => 'Meta Description', 'type' => 'textarea', 'max' => 500],
            'focus_keywords' => ['label' => 'Focus Keywords', 'type' => 'text', 'help' => 'Comma-separated'],
            'og_title' => ['label' => 'OG Title', 'type' => 'text', 'max' => 70],
            'og_description' => ['label' => 'OG Description', 'type' => 'textarea', 'max' => 200],
            'og_image' => ['label' => 'OG Image Path', 'type' => 'text'],
            'og_url' => ['label' => 'OG URL', 'type' => 'url'],
            'twitter_title' => ['label' => 'Twitter Title', 'type' => 'text', 'max' => 70],
            'twitter_description' => ['label' => 'Twitter Description', 'type' => 'textarea', 'max' => 200],
            'twitter_image' => ['label' => 'Twitter Image Path', 'type' => 'text'],
            'canonical_url' => ['label' => 'Canonical URL', 'type' => 'url'],
            'robots' => ['label' => 'Robots', 'type' => 'select', 'options' => [
                'index,follow' => 'Index, Follow',
                'noindex,follow' => 'NoIndex, Follow',
                'index,nofollow' => 'Index, NoFollow',
                'noindex,nofollow' => 'NoIndex, NoFollow',
            ]],
            'hreflang' => ['label' => 'Hreflang (JSON)', 'type' => 'textarea', 'rows' => 3],
            'schema_type' => ['label' => 'Schema Type', 'type' => 'select', 'options' => [
                'Product' => 'Product',
                'WebPage' => 'WebPage',
                'Organization' => 'Organization',
                'LocalBusiness' => 'Local Business',
                'Service' => 'Service',
                'BreadcrumbList' => 'Breadcrumb List',
                'FAQPage' => 'FAQ Page',
                'Article' => 'Article',
            ]],
            'schema_markup' => ['label' => 'Schema Markup (JSON)', 'type' => 'textarea', 'rows' => 5],
            'notes' => ['label' => 'Internal Notes', 'type' => 'textarea', 'rows' => 2],
            'status' => ['label' => 'Active', 'type' => 'toggle'],
        ];

        return $base;
    }
}
